<?php

/*********************************************************************
* Extension configuration file for ext "natural_gallery".
*
* Generated by ext 25-07-2013 09:27 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Natural Gallery',
  'description' => 'Display images as you scroll and enlarged them in a slideshow.',
  'category' => 'plugin',
  'author' => 'Fabien Udriot, Sylvain Tissot, Samuel Baptista',
  'author_email' => 'fabien.udriot@ecodev.ch, sylvain.tissot@ecodev.ch, samuel.baptista@ecodev.ch',
  'author_company' => 'Ecodev',
  'state' => 'beta',
  'version' => '0.9.3',
  'constraints' =>
  array (
    'depends' =>
    array (
      'typo3' => '7.6.0-7.99.99',
      'vidi' => '',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
);
